/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("application")
}

repositories {
    mavenCentral()
}


application {
    mainClass.set("it.unicam.cs.mpmgc.formula1.GUI.MainFX")
}

tasks.named("run") {
    dependsOn(":GUI:run")
}