/*
 * This file was generated by the Gradle 'init' task.
 */

val javaFXVersion = "17.0.13"

plugins {
    id("it.unicam.cs.mpmgc.formula1.java-library-conventions")
    id("application")
    id("org.openjfx.javafxplugin") version "0.0.14"
}

dependencies {
    implementation(project(":app"))
    implementation("org.openjfx:javafx-base:$javaFXVersion")
    implementation("org.openjfx:javafx-controls:$javaFXVersion")
    implementation("org.openjfx:javafx-graphics:$javaFXVersion")
    implementation("org.openjfx:javafx-fxml:$javaFXVersion")
}

javafx {
    version = "17.0.13"
    modules = listOf("javafx.controls", "javafx.fxml")
}

application {
    mainClass.set("it.unicam.cs.mpmgc.formula1.GUI.MainFX")
}
