/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("it.unicam.cs.mpmgc.formula1.java-application-conventions")
    id("application")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

application {
    mainClass.set("it.unicam.cs.mpmgc.formula1.App")
}
